version:  "3.7"
services:
 nginx:
  container_name: nginx 
  image: daocloud.io/library/nginx:1.12.0-alpine
  volumes:
   -  ../volumes/nginx/conf.d/:/etc/nginx/conf.d/
   -  ../volumes/workspace/:/opt/workspace
  ports:
   - "7421:80"
  environment:
   LANG: en_US.UTF-8
  restart : always